# Generated by Django 3.2.9 on 2024-02-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcontent',
            name='order',
        ),
    ]
