# Generated by Django 3.2.9 on 2024-02-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_generatedcontent_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='prompt',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='generatedcontent',
            name='response',
            field=models.JSONField(),
        ),
    ]
