# Generated by Django 3.2.9 on 2024-02-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_generatedcontent_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='response',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
