# Generated by Django 3.2.9 on 2024-02-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_generatedcontent_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='num_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
