# Generated by Django 3.2.9 on 2024-02-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20240214_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='num_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
