# Generated by Django 3.2.9 on 2024-02-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20240217_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='num_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='objective',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatedcontent',
            name='prompts',
            field=models.JSONField(default=None),
        ),
    ]
