# Generated by Django 4.2.10 on 2024-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20240217_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='lesson',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='content',
            new_name='structure',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
