# Generated by Django 4.2.10 on 2024-03-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=200)),
                ('assistant_id', models.CharField(max_length=200)),
                ('num_lessons', models.IntegerField(default=0)),
                ('num_tasks', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('tasks_solved', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('response', models.JSONField(default=None)),
                ('prompts', models.JSONField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GeneratedContent',
        ),
    ]
