# Generated by Django 4.2.10 on 2024-03-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_task_thread_delete_test_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_thread',
            name='prompts',
        ),
        migrations.AlterField(
            model_name='task_thread',
            name='responses',
            field=models.JSONField(default=dict),
        ),
    ]
