# Generated by Django 4.2.10 on 2024-03-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_task_thread_prompts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_thread',
            name='prompts',
            field=models.JSONField(default=dict),
        ),
    ]
