# Generated by Django 4.2.10 on 2024-03-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_rename_responses_task_thread_learning_threads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_thread',
            name='learning_threads',
        ),
        migrations.AddField(
            model_name='task_thread',
            name='learning_thread',
            field=models.JSONField(default=list),
        ),
    ]
