name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up other necessary steps for your deployment

      - name: Deploy to Production
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Execute the command to initiate the deployment
